/**
 * In-memory session store.
 *
 * Maps opaque cookie IDs to a small record. M1 ships memory-only:
 *   - Server restart invalidates all sessions (intentional; see config.ts).
 *   - Cookie value is generated by crypto.randomUUID — 122 bits of entropy is
 *     sufficient for unguessability without persistence.
 *
 * Persistence (sessions.json under HYPHA_DATA_DIR) moves to M3 alongside
 * key persistence.
 */

import { randomUUID } from "node:crypto";

export interface SessionRecord {
  username: string;
  createdAt: number;
  expiresAt: number;
}

export class SessionStore {
  private readonly sessions = new Map<string, SessionRecord>();

  constructor(private readonly ttlSeconds: number) {}

  create(username: string): string {
    const id = randomUUID();
    const now = Date.now();
    this.sessions.set(id, {
      username,
      createdAt: now,
      expiresAt: now + this.ttlSeconds * 1000,
    });
    return id;
  }

  lookup(id: string): SessionRecord | undefined {
    const record = this.sessions.get(id);
    if (!record) return undefined;
    if (record.expiresAt <= Date.now()) {
      this.sessions.delete(id);
      return undefined;
    }
    return record;
  }

  delete(id: string): void {
    this.sessions.delete(id);
  }
}

export const SESSION_COOKIE_NAME = "hypha-session";
